general.import = [
  "~/.config/alacritty/kanagawa.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.85

[font]
normal = { family = "SFMono Nerd Font", style = "Regular" }

[keyboard]
bindings = [
  { key = "Q", mods = "Super", action = "Quit"},
  { key = "C", mods = "Super", action = "Copy"},
  { key = "V", mods = "Super", action = "Paste"},
]
