column_width = 120
line_endings = "Unix"
indent_type = "Space"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
collapse_simple_statement = "Always"

[sort_requires]
enabled = false
