export EDITOR="nvim"
export GOPATH="$HOME/.local/go"
export PATH="$GOPATH/bin:$HOME/.local/bin:$PATH"

# export QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor
# export PLASMA_USE_QT_SCALING=1
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_ENABLE_HIGHDPI_SCALING=1

export CPM_SOURCE_CACHE="$HOME/.cache/CPM"
. "$HOME/.cargo/env"
