export EDITOR="nvim"
export GOPATH="$HOME/.local/go"
export PATH="$GOPATH/bin:$HOME/.local/bin:$PATH"

export CPM_SOURCE_CACHE="$HOME/.cache/CPM"
. "$HOME/.cargo/env"

export LIBRARY_PATH="/opt/homebrew/lib"
